### ISSUE TITLE
error when using linux binary

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/cpp-play#166]
```
/play_client --data-dir=delegate
./play_client: error while loading shared libraries: libdb_cxx-5.3.so: cannot open shared object file: No such file or directory
```

**Comment by clar** [comment]
I think this post explains the reason and gives a solution for it.
http://serverfault.com/questions/470717/why-cannot-make-test-when-installing-openldap

"""
Create file /etc/ld.so.conf.d/db53.conf with following line

/usr/local/db5/lib
Then run ldconfig.
"""

"""
Actually the last line is a simple explanation. The ld.so (dynamic linker/loader) holds a list of directories where libraries reside. The standard(pre-configured) path include /lib, /usr/lib, etc. In this case, libdb-5.3.so is not in any of those path. So we put in a config file to notify it. ldconfig is used to update the link cache(/etc/ld.so.cache), whenever there are changes to those information. So next time you run into similar situation, you can create a new .conf file specific for that library and run ldconfig again.
"""

**Comment by clar** [comment]
I will check with the linux binary and then close it

**Comment by clar** [comment]
ldd shows two dynamic libs are not found

baoh@ubuntu-1-on-second:~/download$ ldd play_testnet_client
        linux-vdso.so.1 =>  (0x00007fff4d7f9000)
        libtcmalloc.so.4 => not found
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007fa00bef2000)
        libdb_cxx-5.3.so => not found
        libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007fa00bc8a000)

We may need to install the lib manully.

**Comment by clar** [comment]
For using linux binary, we need to install some libs manually.

Install packages

    sudo apt-get install libdb++-dev libdb-dev libtcmalloc-minimal4

Create link for TCMalloc library file

    sudo ln -s /usr/lib/libtcmalloc_minimal.so.4 /usr/lib/libtcmalloc.so

**Comment by clar** [comment]
- [ ] TODO: add above comments into linux release package.

**Comment by clar** [comment]
@HackFisher
