### ISSUE TITLE
[UI]应用市场中三个应用的图片部分不能显示

### ISSUE THREAD

**Issue by logxing** [bitsuperlab/cpp-play#176]
![image](https://cloud.githubusercontent.com/assets/7186410/14347561/556de9de-fcea-11e5-9a68-000be41dcf82.png)

**Comment by AlexChien** [comment]
@HackFisher please point qt_play to bitsuperlab/qt_play@7c47cec59f6787396905f56f7ce3bcd190154501

It should have fixed the missing image asset issue.
